# eBPF Packet Logger - top-level orchestration.
#
# This Makefile is the single host-side entry point for running the demo.
# It only ever calls `docker compose` - it never invokes cmake, ninja, or
# the compiler directly. The actual build happens inside the container:
#
#   host:      make up          (this Makefile)
#   container: core-entrypoint.sh
#   container: cmake -> build.ninja -> clang/bpftool/gcc
#
# The in-container `build.ninja` (generated by CMake) and this top-level
# Makefile live in different directories and never interact. There is no
# conflict: this Makefile orchestrates Docker; ninja compiles the code.

# ---- Config -------------------------------------------------------------
COMPOSE      ?= docker compose
SVC_LOGGER   ?= packet-logger
SVC_WIRESHARK ?= wireshark
CTR_LOGGER   := ebpf-packet-logger
CTR_WIRESHARK := ebpf-wireshark
OUTPUT_DIR   ?= output
TRAFFIC      ?= all      # make test TRAFFIC=udp

# Export host uid/gid so containers chown their output artifacts back to us.
# This is what lets you `rm output/*` without "Permission denied" afterwards.
export HOST_UID := $(shell id -u)
export HOST_GID := $(shell id -g)

# Default target: show available commands.
.DEFAULT_GOAL := help

# ---- Targets ------------------------------------------------------------
.PHONY: help up up-d down logs logs-logger logs-wireshark status test decode \
        view-log view-decoded clean fix-perms rebuild

help: ## Show this help.
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

up: ## Start both services in the foreground (Ctrl-C to stop).
	$(COMPOSE) up --build

up-d: ## Start both services detached (background).
	$(COMPOSE) up --build -d
	@echo "Running in background. View logs: make logs   |   Stop: make down"

down: ## Stop both services (decodes capture -> decoded.txt, then clean teardown).
	@# Explicitly decode the pcap while the wireshark sidecar is still running,
	@# rather than relying on its SIGTERM trap (which races with docker kill).
	@if docker ps --format '{{.Names}}' | grep -q '^$(CTR_WIRESHARK)$$'; then \
		if [ -s $(OUTPUT_DIR)/capture.pcap ]; then \
			echo "==> Decoding $(OUTPUT_DIR)/capture.pcap -> $(OUTPUT_DIR)/decoded.txt ..."; \
			docker exec $(CTR_WIRESHARK) tshark -r /work/output/capture.pcap -V \
				> $(OUTPUT_DIR)/decoded.txt 2>&1 \
				&& echo "    Wrote $$(wc -l < $(OUTPUT_DIR)/decoded.txt) lines." \
				|| echo "    tshark decode failed (see $(OUTPUT_DIR)/decoded.txt)."; \
		else \
			echo "==> No capture.pcap to decode (empty or missing)."; \
		fi \
	else \
		echo "==> $(CTR_WIRESHARK) not running; skipping explicit decode."; \
	fi
	$(COMPOSE) down
	@# Belt-and-braces: if a container was force-killed before its trap ran,
	@# the veth pair may linger on the host. Best-effort removal.
	@-ip link del veth0 2>/dev/null || true
	@-ip link del veth1 2>/dev/null || true

logs: ## Tail logs from all services.
	$(COMPOSE) logs -f

logs-logger: ## Tail only the BPF logger service.
	$(COMPOSE) logs -f $(SVC_LOGGER)

logs-wireshark: ## Tail only the tshark sidecar.
	$(COMPOSE) logs -f $(SVC_WIRESHARK)

status: ## Show container status.
	$(COMPOSE) ps

test: ## Send test traffic into the running demo (TRAFFIC=all|icmp|udp|tcp|http).
	docker exec $(CTR_LOGGER) /work/scripts/send-traffic.sh $(TRAFFIC)


decode: ## Decode current pcap to stdout (WRITE=1 saves to output/decoded.txt; FILTER="udp port 9123").
	@if [ ! -s $(OUTPUT_DIR)/capture.pcap ]; then \
		echo "output/capture.pcap is empty or missing. Is the demo running? Try: make up"; \
		exit 1; \
	fi
	@if [ "$(WRITE)" = "1" ]; then \
		echo "==> Writing $(OUTPUT_DIR)/decoded.txt ..."; \
		docker exec $(CTR_WIRESHARK) tshark -r /work/output/capture.pcap \
			$(if $(FILTER),-Y $(FILTER),) -V > $(OUTPUT_DIR)/decoded.txt; \
		echo "    $$(wc -l < $(OUTPUT_DIR)/decoded.txt) lines written."; \
	else \
		docker exec $(CTR_WIRESHARK) tshark -r /work/output/capture.pcap \
			$(if $(FILTER),-Y $(FILTER),) -V; \
	fi

view-log: ## Show the BPF logger summary (output/packets.log).
	@cat $(OUTPUT_DIR)/packets.log 2>/dev/null || echo "No packets.log yet. Start the demo: make up"

view-decoded: ## Show the full tshark decode (output/decoded.txt).
	@cat $(OUTPUT_DIR)/decoded.txt 2>/dev/null || echo "No decoded.txt yet. It's written on 'make down', or run: make decode WRITE=1"

clean: ## Stop services and remove output artifacts (keeps source).
	$(COMPOSE) down -v
	@# Artifacts may be root-owned from a prior run; chown via a throwaway
	@# root container so the rm below never hits "Permission denied".
	@$(MAKE) --no-print-directory fix-perms
	rm -rf $(OUTPUT_DIR)/packets.log $(OUTPUT_DIR)/capture.pcap $(OUTPUT_DIR)/decoded.txt
	@-ip link del veth0 2>/dev/null || true
	@-ip link del veth1 2>/dev/null || true

fix-perms: ## Reown output/* to the current host user (fixes root-owned files).
	@echo "==> chown output/ -> $(HOST_UID):$(HOST_GID)"
	@docker run --rm -v "$(CURDIR)/$(OUTPUT_DIR):/work/output" \
		alpine:latest chown -R "$(HOST_UID):$(HOST_GID)" /work/output

rebuild: ## Force a clean rebuild of the Docker images.
	$(COMPOSE) build --no-cache